server:
  port: 9020
  servlet:
    context-path: /ppi/v2
spring:
  boot:
    admin:
      client:
        url: http://localhost:9040
  application:
    name: booking-service
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookingBD;
    platform: h2
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9015/eureka/
feign:
  circuitbreaker:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

