server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/ppi/v2/users/**
        - id: movie-service
          uri: lb://movies-service
          predicates:
            - Path=/ppi/v2/movies/**
        - id: showtimes-service
          uri: lb://showtimes-service
          predicates:
            - Path=/ppi/v2/showtimes/**
        - id: bookings-service
          uri: lb://bookings-service
          predicates:
            - Path=/ppi/v2/bookings/**