server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/ppi/v2/users/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/ppi/v2/movies/**
        - id: showtime-service
          uri: lb://showtime-service
          predicates:
            - Path=/ppi/v2/showtimes/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/ppi/v2/bookings/**