server:
  port: 9021
  servlet:
    context-path: /ppi/v2
spring:
  application:
    name: showtime-service
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:showtime;
    platform: h2
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/


